CREATE TRIGGER mastery_no_update BEFORE UPDATE ON mastery_decisions BEGIN SELECT RAISE(ABORT,'immutable mastery'); END;
CREATE TRIGGER mastery_no_delete BEFORE DELETE ON mastery_decisions BEGIN SELECT RAISE(ABORT,'immutable mastery'); END;
CREATE TRIGGER skk_no_update BEFORE UPDATE ON skk_decisions BEGIN SELECT RAISE(ABORT,'immutable skk'); END;
CREATE TRIGGER skk_no_delete BEFORE DELETE ON skk_decisions BEGIN SELECT RAISE(ABORT,'immutable skk'); END;
CREATE TRIGGER mastery_insert_guard BEFORE INSERT ON mastery_decisions BEGIN
  SELECT CASE WHEN NEW.status NOT IN ('mastered','needs_revision') OR length(trim(NEW.reason))=0 OR NOT json_valid(NEW.snapshot_json) OR NEW.revision<>COALESCE((SELECT MAX(revision) FROM mastery_decisions WHERE assignment_id=NEW.assignment_id AND competency_id=NEW.competency_id),0)+1 THEN RAISE(ABORT,'invalid mastery revision') END;
  SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM curriculum_assignments ca JOIN basic_competencies bc ON bc.id=NEW.competency_id JOIN core_competencies ki ON ki.id=bc.core_competency_id JOIN class_subjects cs ON cs.class_id=ca.class_id AND cs.subject_id=bc.subject_id JOIN classes c ON c.id=ca.class_id JOIN class_memberships cm ON cm.class_id=ca.class_id AND cm.student_id=ca.student_id JOIN users u ON u.id=NEW.actor_id WHERE ca.id=NEW.assignment_id AND ca.status='active' AND ca.competency_package_id=ki.competency_package_id AND cs.teacher_id=NEW.actor_id AND c.status='active' AND cm.status='active' AND u.status='active' AND u.role='teacher') THEN RAISE(ABORT,'mastery scope') END;
  SELECT CASE WHEN EXISTS(SELECT 1 FROM skk_decisions d JOIN subject_skk_allocations a ON a.id=d.allocation_id JOIN basic_competencies bc ON bc.subject_id=a.subject_id WHERE bc.id=NEW.competency_id AND d.assignment_id=NEW.assignment_id AND d.revision=(SELECT MAX(revision) FROM skk_decisions WHERE assignment_id=d.assignment_id AND allocation_id=d.allocation_id) AND d.status IN ('awarded','recognized')) THEN RAISE(ABORT,'revoke credit first') END;
END;
CREATE TRIGGER skk_insert_guard BEFORE INSERT ON skk_decisions BEGIN
  SELECT CASE WHEN NEW.status NOT IN ('awarded','recognized','revoked','rejected') OR length(trim(NEW.reason))=0 OR NOT json_valid(NEW.snapshot_json) OR NEW.revision<>COALESCE((SELECT MAX(revision) FROM skk_decisions WHERE assignment_id=NEW.assignment_id AND allocation_id=NEW.allocation_id),0)+1 THEN RAISE(ABORT,'invalid skk revision') END;
  SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM curriculum_assignments ca JOIN subject_skk_allocations a ON a.id=NEW.allocation_id AND a.competency_package_id=ca.competency_package_id JOIN class_subjects cs ON cs.class_id=ca.class_id AND cs.subject_id=a.subject_id JOIN class_memberships cm ON cm.class_id=ca.class_id AND cm.student_id=ca.student_id JOIN classes c ON c.id=ca.class_id JOIN users u ON u.id=NEW.actor_id WHERE ca.id=NEW.assignment_id AND ca.status='active' AND cs.teacher_id=NEW.actor_id AND cm.status='active' AND c.status='active' AND u.status='active' AND u.role='teacher' AND NEW.credits=CASE WHEN NEW.status IN ('awarded','recognized') THEN a.planned_skk ELSE 0 END) THEN RAISE(ABORT,'skk scope or credits') END;
  SELECT CASE WHEN NEW.status IN ('awarded','recognized') AND (
    NOT EXISTS(SELECT 1 FROM json_each(NEW.snapshot_json,'$.mastery')) OR
    EXISTS(SELECT 1 FROM curriculum_assignments ca JOIN subject_skk_allocations a ON a.id=NEW.allocation_id JOIN core_competencies ki ON ki.competency_package_id=ca.competency_package_id JOIN basic_competencies bc ON bc.core_competency_id=ki.id AND bc.subject_id=a.subject_id WHERE ca.id=NEW.assignment_id AND NOT EXISTS(SELECT 1 FROM mastery_decisions d JOIN json_each(NEW.snapshot_json,'$.mastery') j ON json_extract(j.value,'$.id')=bc.id AND json_extract(j.value,'$.revision')=d.revision WHERE d.assignment_id=ca.id AND d.competency_id=bc.id AND d.status='mastered' AND d.revision=(SELECT MAX(revision) FROM mastery_decisions WHERE assignment_id=ca.id AND competency_id=bc.id)))
  ) THEN RAISE(ABORT,'incomplete or stale mastery') END;
END;
